-- 가차샵 인기도 정보 업데이트
-- Supabase SQL Editor에서 실행
-- 생성일: 2025-12-14T10:50:51.839Z

UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1973638486' WHERE name = '가챠당';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1536679726' WHERE name = '가챠오션';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1658915181' WHERE name = '나나가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1935233321' WHERE name = '우주가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1258548110' WHERE name = '아이가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1968164380' WHERE name = '지일가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1479787045' WHERE name = '가챠쿠챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1106679886' WHERE name = '놀이터가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2144105878' WHERE name = '브라더굿즈 가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1053738671' WHERE name = '행궁가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2020665191' WHERE name = '꽁주가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1463883932' WHERE name = '가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1056653512' WHERE name = '가챠콩';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1518549247' WHERE name = '달빛가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1578891869' WHERE name = '가챠팝';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1031667649' WHERE name = '당근가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2146485293' WHERE name = '가챠파크';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1699604798' WHERE name = '에브리가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1335741675' WHERE name = '플레이가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1095078930' WHERE name = '가챠&샵';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2043187385' WHERE name = '포켓가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1312871837' WHERE name = '가챠마켓';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1475598442' WHERE name = '가챠용';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1221523316' WHERE name = '가챠네스트';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2017776195' WHERE name = '가챠고';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1023484269' WHERE name = '하이가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1827927909' WHERE name = '애니가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1050945104' WHERE name = '고고샵가챠';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '가챠엑스 명동점';
UPDATE gachashops SET review_count = 1, rating = NULL, naver_place_id = '2086282525' WHERE name = '가챠챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2097400718' WHERE name = '가치가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1744504691' WHERE name = '행궁가챠 가챠챠';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = '677' WHERE name = '가챠양 본점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2045410724' WHERE name = '더가챠 성균관대점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2098730301' WHERE name = '까까가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1230740939' WHERE name = '가챠가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2029000273' WHERE name = '토모가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2080594378' WHERE name = '또또가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2009661948' WHERE name = '가챠팡팡';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2083745454' WHERE name = '여기로가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1140817932' WHERE name = '가챠차';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2063041564' WHERE name = '반야가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2018764441' WHERE name = '호시가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1181910063' WHERE name = '가차';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1106863059' WHERE name = '가차샵';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2036361869' WHERE name = '가차샵 충장로점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1444045477' WHERE name = '가차양신림';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '가차샵노리터 평촌본점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '16817917' WHERE name = '가차제일교회';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '더(The)카페&가차';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '가차들';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1081254217' WHERE name = '새글고가차도';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '38074898' WHERE name = '가차앞골';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '가챠마트 송리단길점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1548717250' WHERE name = '캡슐토이';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1146856174' WHERE name = '코끼리밥 캡슐토이';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1202655207' WHERE name = '캡슐토이뽑기';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1934542445' WHERE name = '캡슐토이 하하가챠';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '캡슐토이월드';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1736047590' WHERE name = '을왕캡슐토이';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1426335618' WHERE name = '캡슐토이샵';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '캡슐토이 인스파이어 엔터테인먼트 리조트';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2058862669' WHERE name = '캡슐플래닛';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1196954471' WHERE name = '호카상점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '럭키포켓';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1404598449' WHERE name = '정스슈퍼';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2012842261' WHERE name = '꽁실가챠샵 화곡점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '33935784' WHERE name = '애니팝';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1178626595' WHERE name = '가샤폰 반다이오피셜샵';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1706079325' WHERE name = '가샤폰스트리트 홍대점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = NULL WHERE name = '가샤폰 반다이오피셜샵 in잠실';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1386718568' WHERE name = '퍼니랜드 서울개봉점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1817180046' WHERE name = '퍼니랜드 서울홍대점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '퍼니랜드 서울인사동점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '지니코인게임랜드 지곡점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1092184751' WHERE name = '퍼니랜드 서울노량진점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2066390111' WHERE name = '행운게임랜드';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1214352217' WHERE name = '국가대표ID게임랜드 강남점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1275706848' WHERE name = '힙플조이';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2062310631' WHERE name = '스마일 게임랜드';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = '38053' WHERE name = '퍼니랜드 경기용인수지점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1793708286' WHERE name = '더뽑기샵';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '팡팡캐릭터인형뽑기';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1373546552' WHERE name = '퍼니랜드 서울시흥점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2092788868' WHERE name = '캑티가챠샵 종각점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2069710320' WHERE name = '니니 명동';
UPDATE gachashops SET review_count = 4, rating = NULL, naver_place_id = '37868039' WHERE name = '애니메클럽';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '퍼니랜드 경기부천점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = '48909' WHERE name = '퍼니랜드 서울코엑스점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1234081584' WHERE name = '퍼니랜드 경기고양신원점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = '1251049419' WHERE name = '퍼니랜드 성남파미어스몰점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '프렌즈게임뽑기 김제점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '38767060' WHERE name = '가챠샵 서면점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '뽑기게임랜드';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '대빵인형뽑기 성신점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1865582374' WHERE name = '퍼펙트게임랜드 수원남문본점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1565157035' WHERE name = '미니돌';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1007834461' WHERE name = '아이디게임랜드';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '보물섬게임랜드';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '38473259' WHERE name = '가챠샵 메나미죠죠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2086114878' WHERE name = '써니사이드 전주가챠샵';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1535990717' WHERE name = '비잉비잉 남포점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2092691329' WHERE name = '봉봉스테이션 신촌점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1284522239' WHERE name = '슈퍼베어 인형뽑기방';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2082913712' WHERE name = '핑크팡';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '펀&펀뽑기샵게임랜드';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2080787828' WHERE name = '얼음왕국 광양394호점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1888817645' WHERE name = '캑티가챠샵 홍대점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2072105741' WHERE name = '브라더굿즈 가챠샵';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1162402030' WHERE name = '브라더굿즈';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '349893378' WHERE name = '가챠샵 전주점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1389163854' WHERE name = '가챠샵';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1271774758' WHERE name = '별보러가챠';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2073624813' WHERE name = '가챠엑스 홍대입구점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '미니돌 구로점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2014310357' WHERE name = '캑티가챠샵 부평점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1568946239' WHERE name = '가챠샵 인천점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2076113979' WHERE name = '쿄우마가챠샵 LC타워점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2048897015' WHERE name = '브라더굿즈가챠샵 광주충장점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2018906593' WHERE name = '구루구루가챠샵';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '1232229506' WHERE name = '호데데가챠샵 오산본점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = '2044505148' WHERE name = '봉봉가챠 광복점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2040147553' WHERE name = '캑티가챠샵 건대점';
UPDATE gachashops SET review_count = 10, rating = NULL, naver_place_id = '2096340512' WHERE name = '캑티 가챠샵 노원점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '티니핑가챠샵 현대프리미엄아울렛대전점';
UPDATE gachashops SET review_count = 0, rating = NULL, naver_place_id = NULL WHERE name = '가챠샵 롯데백화점부산본점';
